# Generated by Django 3.2.7 on 2021-12-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHC', '0003_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='availabile',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='availability',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
